### PR TITLE
RM-18 fix docs build

### PR DESCRIPTION
**Pull request by Brunope**

### CODE REVIEW

**Comment by Brunope** [comment]
```
docs/source/requirements.txt:20: # TODO: try to replace this file in favor of ONE requirements.txt
docs/source/requirements.txt:21: # TODO: add a test to validate docs build that can run locally and in CI


Reduce total number of punchlist violations to 0 or below!

Tasks: TOP => quality
(See full trace by running task with --trace)
Existing violations: 0
Found 2 punchlist violations

Exited with code exit status 1
```

Does this mean I'm not allowed to write TODO?

**Review by ryantimjohn — APPROVED** [review]
Looks good, let's talk through Python version change here on Monday

**Comment by Brunope** [comment]
Gonna wait to merge this until after https://github.com/bluelabsio/records-mover/pull/193 since the airflow version change will affect this

**Comment by ryantimjohn** [comment]
#193 now merged @Brunope!

**Comment by apiology** [comment]
@Brunope:

> Does this mean I'm not allowed to write TODO?

That's just the default setting of a goofy tool called [punchlist](https://github.com/apiology/punchlist) I had configured here.  I generally use those as things I want to finish out before I complete a PR, with the idea that any longer term things I remember to put those into a tracker somewhere else with the rest of the backlog.

If you wanted to change that policy, you could add 'punchlist' to the array here and disable it: https://github.com/bluelabsio/records-mover/blob/master/Rakefile.quality#L21-L31

**Comment by Brunope** [comment]
copied context from my last commit message because github doesn't show those by default

By upgrading the airflow version, pip was unable to be a real dependency
manager and figure out what dependencies it needed to install ???
I tried to give it some hints about what versions of some other
packages it needed, but it didn't help. So I clobbered the whole thing
with the result of `pip freeze` and made a few manual changes necessary
to get things to build.

**Comment by Brunope** [comment]
Take another look at the changes if you want @ryantimjohn , I'll plan to merge this tomorrow

**Pull request merged**
