### PR TITLE
RM-114 remove upper bounds on db-facts

### PR DESCRIPTION
**Pull request by ryantimjohn**

### CODE REVIEW

**Comment by Brunope** [comment]
damn looks like there is indeed some issue with the 1password db-facts  change which is unsettling. the test is simply timing out

**Comment by Brunope** [comment]
nvm it was the gcloud thing, excellent

**Comment by ryantimjohn** [comment]
Also, I ran too many simultaneous checks yesterday and they overwhelmed our very low resource redshift itest instance @Brunope

**Comment by Brunope** [comment]
ah okay that makes sense why it was seeing redshift timeout errors

**Review by Brunope — APPROVED** [review]

**Pull request merged**
